# Generated by Django 3.0.3 on 2020-08-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200823_0500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Photo',
        ),
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostPhotos',
        ),
        migrations.RenameField(
            model_name='postphotos',
            old_name='image',
            new_name='photo',
        ),
    ]
