# Generated by Django 3.0.3 on 2020-10-26 15:23

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201001_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to=post.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=post.models.get_video_upload_path),
        ),
    ]
