# Generated by Django 3.0.3 on 2020-10-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20201027_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish_immediately',
        ),
    ]
