# Generated by Django 3.0.3 on 2020-11-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_postphotos_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
