# Generated by Django 3.0.3 on 2020-10-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedposts',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
