# Generated by Django 3.0.3 on 2020-10-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20201010_1813'),
        ('social_providers', '0002_auto_20201007_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedposts',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Profile'),
        ),
    ]
