# Generated by Django 3.0.3 on 2020-10-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_providers', '0003_publishedposts_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedposts',
            name='network',
        ),
    ]
