# Generated by Django 3.0.3 on 2020-09-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_network_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_token',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.IntegerField(default=0),
        ),
    ]
