# Generated by Django 3.0.3 on 2020-09-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200914_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_token',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
